### ISSUE TITLE
BulkOption is not available

### ISSUE THREAD

**Issue by nmnu** [microsoft/kafka-connect-cosmosdb#148] opened 2020-11-12 11:39 UTC
**## Problem Statement**
At this moment Bulk is not available, and sometimes we get some performance issues

**## Proposed Solution**
Include optional option to use Bulk on CosmosDB

**## Alternative Solutions**
Alternative solution is to have more tasks and partitions on Kafka side, which is not always a possibility

**## Additional context**

## Next Steps
- [ ] Team consensus to proceed 
- [ ] Complete Design Review
- [ ] Schedule Design Session

**Comment by ryancrawcour** [comment] 2020-12-08 01:58
closing as a duplicate of the 2 separate batch items. 
split in to 2 separate issues because 2 separate connectors and the implementation and implications for each differ.

**Closed by ryancrawcour** 2020-12-08 01:58 UTC
Labels: duplicate, wontfix
